language: node_js

node_js:
  - "0.12"
  - "4.0"
  - "4"
  - "5"
  - "stable"

sudo: false

services:
  - xvfb

before_script:
  - export DISPLAY=:99.0

script:
  - npm run lint
  - npm test
  - npm run test-node
